### ISSUE TITLE
Wrong espflash command

### ISSUE THREAD

**Issue by manio** [jessebraham/esp-template#101]
Hi!
I generated the sample program from this esp-template but in the `.cargo/config.toml`
I've finally got:
```
[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor"
```
Since version 2.0 of espflash the `--monitor` parameter is not valid anymore.

**Comment by MabezDev** [comment]
Are you sure? `--monitor` is a valid command for me.

**Comment by manio** [comment]
Sorry, I meant the `cargo espflash` not `espflash`:
```
cargo espflash --monitor 
error: unexpected argument '--monitor' found

Usage: cargo-espflash espflash <COMMAND>

For more information, try '--help'.
```
Closing.

Edit: Moreover I forgot the `flash` command, so this was invalid.
