### ISSUE TITLE
Add support for esp-wifi/esp-openthread in template generation

### ISSUE THREAD

**Issue by MabezDev** [jessebraham/esp-template#109]

**Comment by bjoernQ** [comment]
Also, embassy with or without esp-wifi would probably be a good thing. We just need to find a way to add it in a manageable (i.e. maintainable) way

**Comment by jessebraham** [comment]
I've updated the title to mention `esp-openthread` instead of `esp-ieee802154`; the former did not previously exist, and the latter is not super useful to end-users, IMO.
