### ISSUE TITLE
Generated CI config fails because it doesn't use the Xtensa-enabled compiler

### ISSUE THREAD

**Issue by bugadani** [jessebraham/esp-template#119]
Example run: https://github.com/bugadani/esp32s3-defmt-example/actions/runs/6576956219

**Comment by SergioGasquez** [comment]
Thanks for reporting this! I think the problem is the `--all-targets`, see #120. Removing it should fix the issue.

The Xtensa compiler is [installed and set as default](https://github.com/bugadani/esp32s3-defmt-example/blob/main/.github/workflows/rust_ci.yml#L33-L38)
