### ISSUE TITLE
Using env var in .cargo/config.toml

### ISSUE THREAD

**Issue by Real-YuZhe** [jessebraham/esp-template#126]
Hi, any way I can use env var in config.toml?

`linker = "/home/ci/.espressif/tools/xtensa-esp32-elf/esp-2022r1-11.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc"`

and I have `export CROSS_CIMPILE=/home/ci/.espressif/tools/xtensa-esp32-elf/esp-2022r1-11.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-`

I tryied `linker = "${CROSS_COMPILE}gcc"` but didn't work? Any adea about how to fix it?

**Comment by Real-YuZhe** [comment]
@ teo swee ann 
Any one knows？

**Comment by bjoernQ** [comment]
I don't think it's currently supported by Cargo: https://github.com/rust-lang/cargo/issues/10789
