### ISSUE TITLE
Binary name not correct in `wokwi.toml`.

### ISSUE THREAD

**Issue by hlf20010508** [jessebraham/esp-template#151]
In `wokwi.toml`, it uses `crate_name` as binary name.
But in `Cargo.toml`, it uses `project-name`.
This results in `file not found`.

For example, if the project name is `esp-test`, after `cargo build`, it will build out a binary named `esp-test`, but wokwi will search `esp_test`.

If I change it to `esp_test` in `Cargo.toml`, the output binary name will be `esp_test` which is correct for wokwi.

**Comment by SergioGasquez** [comment]
I guess that we should use `{{project-name}}` instead of  `{{crate_name}`, if you'd like to open a PR it would be appreciated, if not, I'll test it and create a PR on Monday.

**Comment by hlf20010508** [comment]
Ok, I've opened a PR #152.
