### ISSUE TITLE
Include idf components

### ISSUE THREAD

**Issue by floers** [jessebraham/esp-template#173]
Is there a way to import an existing C idf component into a project based on the esp-template? I want to use [epdiy](https://github.com/vroland/epdiy) but I want to write Rust code. The docs in epdiy state that I could just include it in the components folder of another idf project (I assume this is a common way to include dependencies). Is there such a pattern for a cargo first rust esp project?

**Comment by bjoernQ** [comment]
Seems like you are using Rust on top of esp-idf - in that case you are looking for https://github.com/esp-rs/esp-idf-template

This is the repository of the bare-metal template
