### ISSUE TITLE
Archive this repository in favour of using `esp-generate`

### ISSUE THREAD

**Issue by jessebraham** [jessebraham/esp-template#178]
With the first version of [esp-generate](https://github.com/esp-rs/esp-generate/) published, we should focus our efforts there rather than continuing development of this template.

Given the newness of the tool we should probably wait a bit longer before archiving this repository, but I don't think it's worth investing any more development time here, and as such I'm opening this issue as a warning to potential new users.

Once we're convinced that `esp-generate` is mature enough to promote as our officially recommended solution, we can archive this repository.

**Comment by SergioGasquez** [comment]
We should update the documentation in:
- [ ] https://docs.esp-rs.org/book/writing-your-own-application/generate-project/index.html
- [ ] https://docs.esp-rs.org/no_std-training/02_4_hello_world.html
- [x] https://github.com/esp-rs/awesome-esp-rust?tab=readme-ov-file#templates (https://github.com/esp-rs/awesome-esp-rust/pull/44)
- [x] https://github.com/esp-rs/esp-hal/blob/d6f63d67a945dc90ba70c2bca7ac8b2c2d326782/esp-hal/src/lib.rs#L48

Also, we should probably triage the issues in this repo and move any of them to esp-generate if necessary

**Comment by jessebraham** [comment]
Created issues is the relevant repositories for a couple these:

- https://github.com/esp-rs/book/issues/171
- https://github.com/esp-rs/no_std-training/issues/61

Going to open a PR updating the docs in the HAL shortly here, and @SergioGasquez already updated our awesome list.

**Comment by SergioGasquez** [comment]
I'll work on updating the books!
