### ISSUE TITLE
Add an option for an alloc crate

### ISSUE THREAD

**Issue by TheButlah** [jessebraham/esp-template#24]
I'm new to rust on embedded systems. I want to use esp-hal instead of esp-idf because idf has lots of stuff and configuration I dont understand, so being more bare metal will help me learn here.

I am attempting to use the alloc crate, it would be great if the cargo generate for this template prompted the user to ask them if they want to use `alloc`, and gives them a good default global allocator to use, like `esp-alloc`

**Comment by jessebraham** [comment]
Sorry it took me so long, but this is done now!
