### ISSUE TITLE
When do I call init_heap()?

### ISSUE THREAD

**Issue by matthew-a-thomas** [jessebraham/esp-template#37]
I just used `cargo generate` to create a new project for ESP32C3 with allocations via the `esp-alloc` crate. When I build I get this warning message:

```
warning: function `init_heap` is never used
  --> src\main.rs:10:4
   |
10 | fn init_heap() {
   |    ^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default
```

Should I call `init_heap()` first thing in `main()`?

**Comment by MabezDev** [comment]
Yes afaik, this should be called immediately in main. Is this a bug @jessebraham?

**Comment by jessebraham** [comment]
I guess we just forgot to actually invoke that function in `main`, yeah. Oops.

**Comment by matthew-a-thomas** [comment]
Thank you!
