### ISSUE TITLE
How to I customize/add diagram.json for wokwi?

### ISSUE THREAD

**Issue by akashlama1998-icloud** [jessebraham/esp-template#42]

**Comment by MabezDev** [comment]
You can customize the diagram.json in the browser in a custom project, then pass the project ID to wokwi-server by setting the value of `WOKWI_PROJECT_ID`, [here](https://github.com/esp-rs/esp-template/blob/8e6f26c7ec19fce376e8a133d98fd1ace2d6322d/scripts/run-wokwi.sh#L37)
