### ISSUE TITLE
Issues with ESP32S2

### ISSUE THREAD

**Issue by trembel** [jessebraham/esp-template#57]
Hi,
I'm trying to build a library (`no_std`) for the ESP32-S2 (thus no IC crates needed, just architecture needed) using:
```cargo +esp build --target esp32s2-none-elf --release```

However, I get the following mistake.. How can I avoid it:
```
error[E0463]: can't find crate for `core`
  |
  = note: the `xtensa-esp32s2-none-elf` target may not be installed
  = help: consider downloading the target with `rustup target add xtensa-esp32s2-none-elf`
  = help: consider building the standard library from source with `cargo build -Zbuild-std`
```

**Comment by jessebraham** [comment]
Did you try building with the `-Zbuild-std=core` option as suggested by the error? This should already be covered by the `.cargo/config.toml` file so I'm not sure why you're seeing this error, you shouldn't need the command-line option. We'll see if that makes any difference, though.

__EDIT:__ I've just generated a fresh project using the template for the ESP32-S2, and `cargo build --release` succeeds. So not sure what's going on on your end.
