### ISSUE TITLE
Meaning behind esp-template question "Use template default values" is not obvious.

### ISSUE THREAD

**Issue by georgik** [jessebraham/esp-template#89]
Current questions: Use template default values? true/false

The question not provide insight into what is the user selecting.

Recommended change: Use minimalist project profile? yes/no
In case of no, continue with configuration options.

Why is the "default" question not good? Because "default" can mean something else to different people. Default in my case would mean full-blown project with all the bells and whistles, so that I can easily integrate it with all the things used by app developers including CI with containers, Simulation and Debugging.

**Comment by SergioGasquez** [comment]
Hi! Do you think updating the prompt to: `Use template default values? Using default values will set a minimal project configuration.` will be better?

**Comment by georgik** [comment]
What about: `Use minimal project configuration?` Options: yes/no and yes might be set as default answer

**Comment by MabezDev** [comment]
Throwing another option into the hat, what about flipping the question to:

Advanced options? yes/no, the default being no.

**Comment by SergioGasquez** [comment]
> Throwing another option into the hat, what about flipping the question to:
> 
> Advanced options? yes/no, the default being no.

I like this approach, it would require changing all the CI that are building the template since it will require changing the placeholder name and default value, but it might be still worth
