### ISSUE TITLE
"error: linker `xtensa-esp32-elf-gcc` not found" when trying to build for esp32 after following installation instructions from rust on ESP book

### ISSUE THREAD

**Issue by LeahScholten** [jessebraham/esp-template#99]
After following [the instructions for setting up the environment](https://esp-rs.github.io/book/installation/index.html), I created a new project from this template.
Without modifying anything, I got the following error:``
error: linker `xtensa-esp32-elf-gcc` not found
  |
  = note: No such file or directory (os error 2)

error: could not compile `no_std_project_template` (bin "no_std_project_template") due to previous error``
I am trying to build this for the Adafruit ESP32 Feather which uses a 240 MHz dual core Tensilica LX6 microcontroller with 600 DMIPS.
Which according to `cargo espflash board-info` is an "esp32 (revision v3.0)".
How could I fix this?
There is an Arch package for the required linker, but I want to make sure it won't come with a future update with espup.

**Comment by bjoernQ** [comment]
Most probably it's installed by `espup` but it's not on the path. (i.e. double check https://esp-rs.github.io/book/installation/index.html#3-set-up-the-environment-variables )

It's better to avoid installing `xtensa-esp32-elf-gcc` from other sources

**Comment by LeahScholten** [comment]
I ran the `$HOME/export-esp.sh` instead of sourcing it with `source $HOME/export-esp.sh`. I have changed this and it works now. So this issue can be closed. Sorry for the inconvenience.
